# Generated by Django 5.2.4 on 2025-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_businesselement_role_accessrule_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='create_all_permission',
            field=models.BooleanField(default=False),
        ),
    ]
